# Redirect settings
collections:
  redirects:
    output: true

int main(args (1) args(2)){
  //string value can be change when parameter is not allowed.

  if(output == true){
  print(gitdotio.io)
  else{
  print(false)
}

output: gitdotio.io

function == Sting pass Argument > output
parameter == output(args [1] args [2]);

public static void main(String args [])
{
  int main()

  if(i = 0; i < main; i++){
  print(gitdotio.io){
  if(j = i; j > i; j++){
  else{
  print(arguments){
  String(print function){
  //print function is also used when the argument is still functioning;


  parameter(string pass == display)
  int getcout(display)
  if head is NULL;
  return 0;
  else return1 + getcount(head->next);


     Layouts = getcount
     return = display pass == display == argument string;
     if(j = 1; j > cell; j--){
     if i = 0; 
Pivot chart == Entire.cells_Column
Cells == redirects (args)
String value > main > output
Entirecell.Autofill
  redirects == (*int) //print the statement
    Public static void main(string args[]){
              int main()
                  if(print value is == to string value){
                    print == ++1;
                      else(print value is == to rootperson){
                          return 0;

defaults: rootperson; return; print 
  -
    scope: Arguments 
      type: redirects
    values:
      layout: redirect
